Update to v5 schema
vulcanize/eth-ipfs-state-validator pull request #72
Opened 2023-04-24 14:00 UTC by roysc

Basic refactor and CI update

2023-04-25 00:42 UTC, i-norden requested changes
Hmm something is wrong in CI, log messages aren't particularly helpful. Looks like docker is having issues with the "migrations" image (ipld-eth-db). The v5.0.0-alpha version should work but we should change it to v5.0.1-alpha anyways.

2023-04-25 09:00 UTC, roysc commented
Shall we also tag this as v5.0.1-alpha?

2023-04-26 17:42 UTC, i-norden commented
@roysc we should tag this v5.0.0-alpha.

The convention we use for any repo that depends on ipld-eth-db is that its major version should correspond to the major version of the version of ipld-eth-db that it works with. The minor and patch versions float independently for each repo, so that you can make changes to those codebases that doesn't require changing the version of ipld-eth-db being used. Likewise, changes to ipld-eth-db which don't break backwards compatibility with dependent repos should bump the minor or patch version and any schema change that breaks backwards compatibility should be a major version change.

2023-04-26 17:46 UTC, i-norden approved these changes

2023-04-29 06:40 UTC, merged